### ISSUE TITLE
Small mistakes in microbenchmark code

### ISSUE THREAD

**Issue by jakobgetz** [sola-st/wasm-call-graphs#2]
Going through the Microbenchmarks I notice some small issues:
* Microbenchmark 14 `microbenchmarks/indirect-call-index-expression/main.wat` line `25`: Wrong function index inserted into table. Inserted should be `$not-reachable` instead of `$b`.
* Microbenchmark 20 `microbenchmarks/indirect-call-index-expr-load-interprocedural-param/main.wat` is missing completely
* Microbenchmark 21 `microbenchmarks/indirect-call-index-expr-load-interprocedural-result/main.wat` comment states function id is `$call_indirect` but it is actually `$index`

**Comment by danleh** [comment]
Thanks for notifying us of the issues (and sorry for the late reply)!
* wrt. microbenchmark 14 (I guess you meant `indirect-call-expr-const` since there is no `indirect-call-index-expression`): fixed
* wrt. microbenchmark 20: source file added back in [c3d5e78](https://github.com/sola-st/wasm-call-graphs/commit/c3d5e781d4a48e63910741e793c2311370bdb935), that was accidentally removed in [a539be0](https://github.com/sola-st/wasm-call-graphs/commit/a539be0e1682e54376676c39a9065f7d346df549) (I believe @michelledaviest removed the output files of the static analysis tools and the source file accidentally got selected as well)
* wrt. microbenchmark 21: fixed
